"""
seed_package_master.py — produce a starter ``data/package_master.yaml``
from the current enriched inventory.

Reads vdl_inventory_enriched.csv, groups rows by ``app_name_abbrev``, and for
each abbrev emits:

  - the most-frequent ``app_name_full`` as ``canonical_name`` (best guess only)
  - the most-frequent non-empty ``pkg_ns`` as ``pkg_ns`` (best guess only)
  - a commented-out block listing every distinct ``app_name_full`` /
    ``pkg_ns`` value seen, with row counts, so a human can curate

Output is written to ``data/package_master.seed.yaml`` for review. The
maintainer hand-edits it into ``data/package_master.yaml`` after resolving:
  - the 14 inconsistent ``app_name_full``s from assessment §3.3
  - the 5 multi-abbrev consolidations from assessment §3.4
  - any obviously-wrong "most-frequent" canonical picks

Usage:
  python3 scripts/seed_package_master.py
  python3 scripts/seed_package_master.py --inventory PATH --out PATH
"""

from __future__ import annotations

import argparse
import csv
import logging
from collections import Counter, defaultdict
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_INVENTORY = Path("/home/rafael/data/vista-docs/inventory/vdl_inventory_enriched.csv")
DEFAULT_OUT = Path(__file__).resolve().parent.parent / "data" / "package_master.seed.yaml"


def collect(inventory: Path) -> dict[str, dict]:
    """Group inventory rows by app_name_abbrev and collect distributions."""
    by_abbrev: dict[str, dict] = defaultdict(
        lambda: {"names": Counter(), "pkg_ns": Counter(), "rows": 0}
    )

    with inventory.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            abbrev = row.get("app_name_abbrev", "").strip()
            if not abbrev:
                continue
            entry = by_abbrev[abbrev]
            entry["rows"] += 1
            name = row.get("app_name_full", "").strip()
            if name:
                entry["names"][name] += 1
            ns = row.get("pkg_ns", "").strip()
            if ns:
                entry["pkg_ns"][ns] += 1

    return dict(by_abbrev)


def render(by_abbrev: dict[str, dict]) -> str:
    """Render the collected data as a starter package_master YAML document."""
    lines: list[str] = [
        "# data/package_master.seed.yaml",
        "# Auto-generated by scripts/seed_package_master.py",
        "#",
        "# Hand-curate into data/package_master.yaml:",
        "#   - confirm canonical_name (the most-frequent variant is only a guess)",
        "#   - resolve assessment §3.3 inconsistencies (14 abbrevs)",
        "#   - resolve assessment §3.4 multi-abbrev consolidations (RUM/KMPR, etc.)",
        "#   - set canonical_pkg + aliases for consolidated packages",
        "",
        "packages:",
    ]

    for abbrev in sorted(by_abbrev):
        entry = by_abbrev[abbrev]
        names = entry["names"].most_common()
        ns_choices = entry["pkg_ns"].most_common()
        canonical_name = names[0][0] if names else ""
        canonical_ns = ns_choices[0][0] if ns_choices else ""

        lines.append(f"  {abbrev}:")
        lines.append(f"    canonical_name: {_yaml_str(canonical_name)}")
        lines.append(f"    pkg_ns: {_yaml_str(canonical_ns)}")
        lines.append(f"    canonical_pkg: {_yaml_str(abbrev)}")
        lines.append("    aliases: []")

        if len(names) > 1:
            lines.append(f"    # ⚠ {len(names)} distinct app_name_full values seen:")
            for name, count in names:
                lines.append(f"    #     [{count:>4}]  {name}")
        if len(ns_choices) > 1:
            lines.append(f"    # ⚠ {len(ns_choices)} distinct pkg_ns values seen:")
            for ns, count in ns_choices:
                lines.append(f"    #     [{count:>4}]  {ns}")
        if entry["rows"] and not ns_choices:
            lines.append(f"    # ⚠ pkg_ns is blank in all {entry['rows']} rows")
        lines.append("")

    return "\n".join(lines)


def _yaml_str(value: str) -> str:
    """Quote a string for safe YAML emission (no newlines / colons-no-space risk)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--inventory", type=Path, default=DEFAULT_INVENTORY)
    p.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = p.parse_args()

    if not args.inventory.exists():
        raise SystemExit(f"inventory CSV not found: {args.inventory}")

    by_abbrev = collect(args.inventory)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(by_abbrev), encoding="utf-8")

    inconsistent = sum(1 for e in by_abbrev.values() if len(e["names"]) > 1)
    multi_ns = sum(1 for e in by_abbrev.values() if len(e["pkg_ns"]) > 1)
    no_ns = sum(1 for e in by_abbrev.values() if not e["pkg_ns"])

    logger.info("Wrote %s", args.out)
    logger.info("  abbrevs: %d", len(by_abbrev))
    logger.info("  abbrevs with multiple app_name_full: %d  (assessment §3.3)", inconsistent)
    logger.info("  abbrevs with multiple pkg_ns:        %d", multi_ns)
    logger.info("  abbrevs with blank pkg_ns:           %d  (assessment §3.6)", no_ns)


if __name__ == "__main__":
    main()
